// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                  uuid.UUID        `json:"id"`
	Email               string           `json:"email"`
	Password            string           `json:"password"`
	Verified            *bool            `json:"verified"`
	RefreshTokenVersion int32            `json:"refresh_token_version"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Info      *string          `json:"info"`
	Image     *string          `json:"image"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	AccountID uuid.UUID        `json:"account_id"`
	Name      string           `json:"name"`
	Bio       *string          `json:"bio"`
	Image     *string          `json:"image"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
